### ISSUE TITLE
nothing happen

### ISSUE THREAD

**Issue by ghost** [mdgrs-mei/posh-work-time-tracker#1] opened 2023-07-28 23:23 UTC
nothing showing on my Win10 host, when trying to execute various examples execution hangs on Show-taskbaritem

**Comment by mdgrs-mei** [comment] 2023-07-29 02:14
Sad news, but thank you for your report. 

Did you see any error? Assuming you are using posh_work_time_tracker and not talking about the PoshTaskbarItem module, could you try the following?

1. Right click the posh_taskbar_item shortcut and open Properties
1. Copy `Target` in the shortcut properties
1. Open Windows PowerShell terminal and paste the copied string
1. Remove `-WindowStyle Hidden` parameter and press Enter
1. See if any error is shown on the console

The command in the step 4 should look like this:

```
C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe -NoProfile -ExecutionPolicy Bypass -File "path-to-posh-worktime-tracker\src\posh_work_time_tracker.ps1" "your-user-dir\posh_work_time_tracker"
```

**Comment by FranVoz** [comment] 2023-08-03 06:51
Hi, I was indeed talking about the PoshTaskbarItem module, sorry if I reported in the wrong place

**Comment by mdgrs-mei** [comment] 2023-08-03 09:46
@FranVoz Wrong repo but it's ok. Could you give us a little more information?

- Is there any error when you call Show-TaskbarItem?
- Does `New-TaskbarItem | Show-TaskbarItem` hang too?

**Comment by FranVoz** [comment] 2023-08-03 11:02
New-TaskbarItem | Show-TaskbarItem  hangs too, no error displayed. Either running as admin or local logged on user.
I see now that something is created when running as local user but it's not quite what I expected, see screenshot : 

![image](https://github.com/mdgrs-mei/posh-work-time-tracker/assets/139129829/55b557dc-c300-4d78-9693-54514ecf915d)

**Comment by mdgrs-mei** [comment] 2023-08-03 13:26
Windows merges the taskbar icons from the same executable (powershell.exe) into one icon so it's unfortunately an expected behavior if you are not using other terminal apps like Windows Terminal. To make a dedicated icon for your script, you have to create a shortcut which you will make in the end. 

Please see "Changing application icons" section in the README: https://github.com/mdgrs-mei/PoshTaskbarItem#changing-application-icons

**Comment by mdgrs-mei** [comment] 2023-11-11 01:30
Closing this issue as it seems to be an expected behavior.

**Closed as completed by mdgrs-mei** 2023-11-11 01:30 UTC
